### ISSUE TITLE
librpi_gpio_ext not exist on NanoPi NEO2

### ISSUE THREAD

**Issue by guyluz11** [danrubel/rpi_gpio.dart#15]
Getting this error: 
`librpi_gpio_ext.so: cannot open shared object file: No such file or directoryerror: library handler failed`

On the NanoPi NEO2.

Can you add support for NanoPi NEO2 by default ?

**Comment by guyluz11** [comment]
`pub global run rpi_gpio:build_lib`
```
Dart VM... /home/pi/git/dart-sdk/bin/dart
Dart SDK... /home/pi/git/dart-sdk
Building library in /home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_gpio-0.5.0/lib
rpi_gpio version 0.5.0
building rpi_gpio in /home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_gpio-0.5.0/lib/src/native

/home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_gpio-0.5.0/lib/src/native/build_lib: 29: /home/pi/.pub-cache/hosted/pub.dartlang.org/rpi_gpio-0.5.0/lib/src/native/build_lib: g++: not found
```

So I did `sudo apt install g++` and it pass the `pub global run rpi_gpio:build_lib`

**Comment by guyluz11** [comment]
`dart bin/example.dart `

```
Unhandled exception:
RpiGpio initialization failed: -1
#0      new RpiGpio (package:rpi_gpio/rpi_gpio.dart:26:7)
#1      main (file:///home/pi/git/SmartDeviceDart/bin/example.dart:12:20)
<asynchronous suspension>
#2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
````
