### ISSUE TITLE
is it possible to compiling on windows?

### ISSUE THREAD

**Issue by celalaslan2001** [danrubel/rpi_gpio.dart#22]
Hi Danrubel. I m new on dart and sorry for asking stupid question. I want to compile your examples on win10 and upload to rpi with lineage os. I m using VSCode and  "pub global activate rpi_gpio" is completed succesfully.
 
flutter pub global activate rpi_gpio
Package rpi_gpio is currently active at version 0.7.2.
Resolving dependencies...
The package rpi_gpio is already activated at newest available version.
To recompile executables, first run `global deactivate rpi_gpio`.
Activated rpi_gpio 0.7.2.

 But  pub global run rpi_gpio:build_native get errors like below.
PS C:\Users\celal\Desktop\rpi_gpio.dart-main\bin> dart run build_native.dart
Dart VM... C:\flutter\bin\cache\dart-sdk\bin\dart.exe
Dart SDK... C:\flutter\bin\cache\dart-sdk
Unhandled exception:
ProcessException: The system cannot find the file specified. 

  Command: C:\flutter\bin\cache\dart-sdk\bin\pub list-package-dirs
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:476:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:619:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      main (file:///C:/Users/celal/Desktop/rpi_gpio.dart-main/bin/build_native.dart:26:15)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

How can i add C:\flutter\bin\cache\dart-sdk\bin\pub list-package-dirs?
Any response at any time would be appreciated!
Bst Rgds,
celal

**Comment by danrubel** [comment]
No worries. Happy to help as I am able.

The `rpi_gpio` package is designed to be compiled on the RPi itself and has only been tested with the Raspberry Pi OS.
* copy/clone your application onto the RPi
* cd to the directory containing your application (the directory containing your Dart application's `pubspec.yaml` file)
* follow the setup instructions on https://github.com/danrubel/rpi_gpio.dart#setup

Please let me know how it goes.
