### ISSUE TITLE
Exception when interrupts are disabled

### ISSUE THREAD

**Issue by danrubel** [danrubel/rpi_gpio.dart#7]
Version 0.2.1

Unhandled exception:
Uncaught Error: The null object does not have a getter '_events'.

NoSuchMethodError: method not found: '_events'
Receiver: null
Arguments: []
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      Gpio._checkDisableAllInterrupts (package:rpi_gpio/rpi_gpio.dart:112:25)
#3      Pin.events.<anonymous closure> (package:rpi_gpio/rpi_gpio.dart:263:24)
#4      _StreamController._recordCancel (dart:async/stream_controller.dart:647)
#5      _ControllerSubscription._onCancel (dart:async/stream_controller.dart:814)
#6      _BufferingStreamSubscription._cancel (dart:async/stream_impl.dart:240)
#7      _BufferingStreamSubscription.cancel (dart:async/stream_impl.dart:201)
#8      _CommonPinSensor._cancel (package:lake_utilities/sensors.dart:133:67)
#9      _StreamController._recordCancel (dart:async/stream_controller.dart:647)
#10     _ControllerSubscription._onCancel (dart:async/stream_controller.dart:814)
#11     _BufferingStreamSubscription._cancel (dart:async/stream_impl.dart:240)
#12     _BufferingStreamSubscription.cancel (dart:async/stream_impl.dart:201)

**Comment by danrubel** [comment]
Fixed in 0.2.1+1
